name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run ci

    - uses: actions/checkout@v2
    - name: Commit Badges
      if: ${{ matrix.node-version == '14.x' }}
      run: |
        git status
        git add .
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -am "Updated Basges"
        git push
